language: node_js
sudo: false
node_js:
- '6'
- '7'
- '8'
cache: yarn
script:
- gulp test
after_success:
- npm install codecov codacy-coverage
- cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
addons:
  srcclr: true
env:
  global:
  - secure: oDlqShyGPGiEzlbYcfFs2ljtTTylXB5XT/tOcDlgqkVPvSvjc9aF7ycDK2lGPuSSRgt+h8UcOHPTQBRHWe6qQyn3jIwwlpzkCxY6GTDLioI5AW19YNcBC4+6miJ03N6ho7BNaGqp58wo4JzavdPcIaOiAGFYCTE6TJxB1Hjvsqp8X8Tp64gnIXx8QhDnS1os00JVdN9rKdsqxWgyW3yVgyU/BFPeib7lpHsRaM6A/K7QMDLWy9fZvwr0jwVI7/oToXq367cGqFn6bnAtvDgMhvIvAnQqRHK/qVkEsusIwsf6kdNus5G6AusDXeXzU5QandS2ZR82rfYBcI1HceefzpjmKbQmYonoIYdIdA82AXgPHwDLUWoUuDeiEDIfdGHjCSzryclu8kECz5q8ynCN2w/3hS7IKQs9YKEUC2BhmD/PGFIXzXgmWqiHjYF7uLspCDvlTsVBHSqAPM9r1mWcWJtim8sF3EwqYwSANIvSSHwPqtgExBQnXtJugG2FmxqFR4cfNgvugVKZigi9neK0ylPyzZg3InrE4a+VGdqjLWTMuosQtCBeBmJ4UWuhhKcy+BWpuIfh12QWDyzlh0t1VDAv+mo6l92+aLzetPjtXIMXRsHGJ3EiTd1CFImsq7jFK5hunEdBgHssrke3XGBElwxtJ29GbDZ5Uk7gX+VNupA=
  - secure: VYepVqIWzhz6pZmYclbU45iqL0DLDbZwQrJzhVJ+A8fIU6kUaIf2cTUmQfctLvcA8xqVEY21UABTQ5hC0fkWkTJ2gaGKS2mkxJldmltI259Mn9M8j9dJMrBs+D4iav3vYCTTd03I8d9/NIHjzuX6G3lCeYinBV824luI158CytA9Q/nmTFkdnSgfTW9r5sUSgNiEuHaWdo89zqAWk+t7ZzYSYNmQM9Pl+xarFYs+NMmn5k8N75UrSXxGUouteENOAPxO/JTHmjl0BcTu0USWa/ZAkIU7Sq3/uaj71X7mRl52RMjMdM1fi7PEoWfyZI/2GfDNom87LfYU1Eo25PeyfyZDMNU0FN83RUgCqOvWyOG3AEOjeiMsatF/hhhu+q8ufpa/gr0z+LVZNfsCkvJh12EdM1F+JuSnmKA+lCGcMiYjUGF2k18TcYcOvasJcVr1gZlFzc9Yodp6rcNsH7Ti/5IL4cx33uilkX02SFyWOZQZ/8yYl4Q+b4Q26n6YDZujOSssdzkwQYOSa+bg+J3mpcpHM6a1BgY588wx+msArEzFUtwic2wWlXllC5nOVa9gvmZGN/5u4D2u4PpBBQ3JvcD6fmSjUC9hAgkREBl/kDaDRafuHfdRBaW/eGjq/I1OQfpS5/WiJ+NXnlG68qTpnmvD62qSmcpurStTA9nu1o8=
