language: node_js
sudo: false
node_js:
- '6'
- '7'
- '8'
cache: yarn
script:
- gulp test
after_success:
- npm install codecov codacy-coverage
- cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
addons:
  srcclr: true
env:
  global:
  - secure: cfRihTqOtBGX/to5NE68x6OpNQlNFBzS3J3nYltIyfZkwIPmRx2wNWKWvN6RbuVvvWj17xgIJUwCfMO+g8AiPkkAh7sne0DEsKweJkY7KUtoHpZooxpqZP+k2ofr9FJrzp91IDMtVlmx2T5N1B6GlBt6gQs2GJ+nMgTCeNizHUgydKB09cZip0iWBuuzAC8K+ta4LMKdlV3lkJRH1dXRrIk5AwH7CLlUlDqhzbL1krccL2OKdUB3KTkQzlyHIsJdB4mEjv3WAjbUQllZFVfDpMEY+pLh/5LRVUwVkhG0xOm4omSqiT7knC/2fpCsX7qp3tV6L11DNFev8fWiazdO2vh+bM7eXzDFE37bOMg99x9sJk1UA6vJaeTc0S06SGCLDzAyoL/uFNKhlRE/1tRMytSLOaFnqENCHkV/XoVm8e/JaEJdBxHG6FndtOrzsqvP5WN2PXL6D/X7+KUrOIA9lKbHjm5zGHV9FmmBW8nDxExrUajNB9jrEydIyqwFTqB7AYN/pZHBk/K3EX3vUIx5s7b/euMRYrmwtsnRvjs6jALXlKcCsD8GHI8lE5XmDaU+VxkrdFSBP/GGiRXMqGnBU2iFEQqMKanusR4VpWH2WJ5u3CB7Aw0mEfICrpSFvKAkP4LOEf7dt7Ar2eR9hrxlo5rbP8EAYJOe5P+qCTA+5hU=
  - secure: brbbnXIv/gBeOAHUMvPASaThg6b1N7MxyEExSHU6zCQ3a5hFZBg57+ZoT+xjiYGEmYbvzItMzRDN1YS9SyAR72VJVRVsQpHaFgidop1QzDtc3GkihuIEKtMLSwtCckv5h6VipW6LVm/IrrEEhD+frMhH0k1ct0E9Lg2mk2gzX6FsGB6gZJBHS0Zq+jyy6ZlhrvD5pO0P8cC2YPWgHOUkw3cvqeLDLGqJlyuANqhA4U+VlUxvtrYj4rbEhR3iyiAFZS1Lf55TrT1Re0kqMUE9ElXftuGP9bFiOVlTGWAi3Vcb9TTD3GJNgG5FrRcbuHDKxkZeDgfYL7hzr+5g75oWuIu9L8ZewqYcdJgRf/dEZpQiuRGwa4xh+z4fo56g8rzZE/lpwj6tYBGdx3fOUIIUELGWfwxWU8NyjLxAvnfJHHt2IH3c+NhF+U1aKTc1ZMXFnQlhJuBQhtx45if5X0B8GYycGXVEi87ch2v9OjQNZvAag9zOKg+FH3AD3Jp5LlTOVqLP9Y3QUqs80Z4fg7ozBODLP6kk8tgGT3R1GNuYBHzbmu16RyQ+pjAPvrQG8r0DwXEd5/rycb+6yOOZXnOylFQKR08HbrDp2JilhHoRducHL3Z2yNSe12GIsWbAlBX1Kn6AyEVdf0b2FE6v7JESu5MSrwmr9dHp9HvpLdVz+AA=
