language: node_js
sudo: true
node_js:
- '6'
- '7'
- '8'
cache: yarn
script:
- mocha test/integration/main.test.js
after_success:
- npm install codecov codacy-coverage
- cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
addons:
  srcclr: true
env:
  global:
  - secure: ofbhXt7JA3cL2g8buNEZFnaYG/J7ZfmHi+Q6MrV9DpXTUurwzGlAEvMUdFQoVo4jx4ynOz0QavEIrneUArDuRbpIUnXd20v6S1e+gl6e7FpDUH3ywLJPPHQRx22vZgmeCGI9eBmSqLWvgfA5OwOhoNEPp/phypLpoWR7Gs9uKkqw7CpeHf6iKUd9EHMVFiE9qjJSNRUQkEZyiUdegoaW/ODF2m9gGn57qKyFZBl42+XLm6UwTIiaHS3V0JDprx+X1gNO/kNBmlxnJDAYZo0qJEc0irbDmKMB9sQnXWX3iaoTQe35Nyd7Dsq3X6FZ2IDo/3Y5j94LMj6A3rTXEBGw/IOSzgEP9F85876m1BwFYLOmEIuSomzR0Pf5e4kF1tM3FLrbZJTRMb6H+zs71iMxcfLhwitF1huUBhoGRjj5yjMuEw1xzzS/etQeOXOiB0lw1Ujq6FDajWjrKQNLtVaYPt1bHe0Z2oTqGbRAIokaufDHrJTKqDmV2DO0XbiEuR0tnykK4fzrRpxMj4I6hn2cYNkxE2p7OGWXSH1lxemXOWeEHVoQ5nZ9VfvBS+9la1Tp5k+jWRAoQ2m2H5axOl9Sai42/qF+Ywx0Mpj+5+4C6sThLSc7BeAw1sVhiLbs3gCTb+RvBGXofWWwS4pVNEu4cqWbEP7ZZbQbc1bOELoa+Y8=
  - secure: BA94atvjMn8mxzkuPw32dAHjIKWSTpDu/f/DCcbC0XoZQMnLSnD2T5qq3vK+i8ErGAV9r+IFfbOeYdtQF8p92NlS2Np87fFuHtshmacCHR+UBleTUu6i1hs3c6ldRk4YKht55y3WvqVxBw+ILbNYVkcL75s+k+sTUS5TaqXsr4NnNxsIKeceifOsyK8S6duDeGST1f0Yp2w8PLawDcAxbxMk8pNWIPoD7RsZYAcxLmxkBgQZIBRDDGdNvxlq8RzaXSH1Wq8GU4SFJhh28sEtmIbnoNmOoCN/hApng34ehzz4MF6/GeNVLIhciaPQzH5vs+M1l8ost9OfshE5kEgUvQ76FeXZkCd4LqtbIWm0VroXNT5g0i88344k10iDn9FHADKvWqI8TOr9bVDkiKV8XAT0K9G4pG/vDF1V93BwiQcUOzu8JBkX4hnQF2bQcOBHH/YpGCcv3CmVEk3/VczK540yj5TuaTYkyuf9/jSHlIAZ9hwAslUrTnNuVFkd+C/QhB19BV6r5yeybzMkorOa4t55FLl3/CtviMzbpF5ExYI0lh01qGryUP3bzxP83MaEDy7f/jBydfW9ekX5/nilbD0tvSQKfCQ5PU+FIQrNI3I2etu2u9VYkURo3eNmThqCvUlYr6AfJ92Agw8p++wYQXDX2mJA+AL4q48/kc1Bp0E=
